#!/bin/sh
# Resolve all dependencies that the application requires to run.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

uv venv $VIRTUAL_ENV

echo "Installing development dependencies..."
uv sync --group dev
