"""Comprehensive API smoke-test for pypaperless.

Runs against the dev PaperlessClient instance configured via the repo-root .env
(PYPAPERLESS_URL / PYPAPERLESS_TOKEN / PYPAPERLESS_TEST_DOC; see .env.example).
PYPAPERLESS_TEST_DOC is used as the test document.

Exit code 0  → all sections green
Exit code != 0 → at least one section failed (printed in red)
"""

# ruff: noqa
# mypy: ignore-errors

# This file was fully automatically generated by GitHub Copilot (Claude Sonnet 4.6).

import argparse
import asyncio
import logging
import traceback
import uuid
from collections.abc import Callable, Coroutine
from typing import Any

import httpx

from pypaperless import PaperlessClient
from pypaperless.builders import SearchQuery
from pypaperless.models.correspondents import CorrespondentDraft
from pypaperless.models.custom_fields import (
    CustomFieldIntegerValue,
    CustomFieldStringValue,
)
from pypaperless.models.document_types import DocumentTypeDraft
from pypaperless.models.documents import DocumentCustomFieldList, DocumentDraft, DocumentNoteDraft
from pypaperless.models.share_links import (
    ShareLinkBundleDraft,
    ShareLinkDraft,
    ShareLinkFileVersion,
)
from pypaperless.models.storage_paths import StoragePathDraft
from pypaperless.models.tags import TagDraft
from pypaperless.builders.custom_fields import CustomFieldQuery
from pypaperless.exceptions import DeletionError, JsonResponseWithError

from _dev_env import load_dev_env


async def _retry_flaky[T](coro_factory: Callable[[], Coroutine[Any, Any, T]]) -> T:
    """Run a server-flaky operation, retrying once after a short delay.

    The Paperless-ngx notes endpoints intermittently fail while the search
    index writer is busy (HTTP 500 on delete, HTTP 200 with an error payload
    on save). One retry after a pause reliably clears the transient without
    masking real regressions - the retried call still has to succeed.
    """
    max_retries = 3
    retries = 0
    while retries < max_retries:
        try:
            return await coro_factory()
        except (DeletionError, JsonResponseWithError):
            retries += 1
            if retries < max_retries:
                await asyncio.sleep(5)
            else:
                raise
    raise Exception("Failed after max retries")


# ── PDF helper ────────────────────────────────────────────────────────────────


def _make_unique_pdf(token: str) -> bytes:
    """Build a minimal valid single-page PDF with *token* embedded in the Info dict.

    Xref offsets are computed dynamically so the file is always valid —
    unlike a hardcoded template that breaks when any bytes are prepended.
    Each call with a different token produces a unique hash, which defeats
    PaperlessClient-ngx duplicate detection.
    """
    token_bytes = token.encode()
    header = b"%PDF-1.4\n"
    obj1 = b"1 0 obj<</Type/Catalog/Pages 2 0 R/Info 4 0 R>>endobj\n"
    obj2 = b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
    obj3 = b"3 0 obj<</Type/Page/MediaBox[0 0 3 3]/Parent 2 0 R>>endobj\n"
    obj4 = b"4 0 obj<</Subject(" + token_bytes + b")>>endobj\n"

    off1 = len(header)
    off2 = off1 + len(obj1)
    off3 = off2 + len(obj2)
    off4 = off3 + len(obj3)
    xref_off = off4 + len(obj4)

    xref = (
        b"xref\n0 5\n"
        b"0000000000 65535 f \n"
        + f"{off1:010d} 00000 n \n".encode()
        + f"{off2:010d} 00000 n \n".encode()
        + f"{off3:010d} 00000 n \n".encode()
        + f"{off4:010d} 00000 n \n".encode()
        + b"trailer<</Size 5/Root 1 0 R>>\n"
        + f"startxref\n{xref_off}\n%%EOF\n".encode()
    )
    return header + obj1 + obj2 + obj3 + obj4 + xref


async def _await_task_and_cleanup(
    p: PaperlessClient,
    task_id: str,
    label: str,
    *,
    timeout: int = 45,
) -> None:
    """Poll *task_id* until it finishes, then delete the resulting document.

    Uses ``Task.related_document_ids`` to obtain the created doc ID.
    """
    from pypaperless.models.tasks import TaskStatus

    doc_id: int | None = None
    deadline = asyncio.get_event_loop().time() + timeout
    task = None
    while asyncio.get_event_loop().time() < deadline:
        task = await p.tasks(task_id)
        if task is None:
            break
        if task.status in (
            TaskStatus.SUCCESS,
            TaskStatus.FAILURE,
            TaskStatus.REVOKED,
        ):
            if task.related_document_ids:
                doc_id = task.related_document_ids[0]
            break
        await asyncio.sleep(1)

    if task is not None and task.status == TaskStatus.FAILURE:
        ok(
            f"cleanup [{label}]: task failed – nothing to delete",
            f"result_data={task.result_data!r}",
        )
        return

    if doc_id is not None:
        try:
            doc = await p.documents(doc_id)
            deleted = await p.documents.delete(doc)
            ok(f"cleanup [{label}]: deleted doc #{doc_id}", f"deleted={deleted}")
        except Exception as exc:
            fail(f"cleanup [{label}]: delete doc #{doc_id}", exc)
    else:
        ok(
            f"cleanup [{label}]: doc not found after {timeout}s",
            "still processing or duplicate-rejected — skip",
        )


logging.basicConfig(level=logging.WARNING)

# ── Connection ────────────────────────────────────────────────────────────────
_env = load_dev_env()
PAPERLESS_URL = _env.url
PAPERLESS_TOKEN = _env.token.get_secret_value()
TEST_DOCUMENT_ID = _env.test_doc
PAGE_SIZE = 500

# ── Terminal colours ──────────────────────────────────────────────────────────
GREEN = "\033[32m"
RED = "\033[31m"
YELLOW = "\033[33m"
CYAN = "\033[36m"
RESET = "\033[0m"
BOLD = "\033[1m"

# ── Result tracking ───────────────────────────────────────────────────────────
_passed: list[str] = []
_failed: list[tuple[str, str]] = []


def _hdr(title: str) -> None:
    print(f"\n{BOLD}{CYAN}{'─' * 60}{RESET}")
    print(f"{BOLD}{CYAN}  {title}{RESET}")
    print(f"{BOLD}{CYAN}{'─' * 60}{RESET}")


def ok(label: str, detail: str = "") -> None:
    suffix = f"  {YELLOW}{detail}{RESET}" if detail else ""
    print(f"  {GREEN}✓{RESET}  {label}{suffix}")
    _passed.append(label)


def fail(label: str, exc: BaseException) -> None:
    msg = f"{type(exc).__name__}: {exc}"
    print(f"  {RED}✗{RESET}  {label}")
    print(f"      {RED}{msg}{RESET}")
    _failed.append((label, msg))


async def check(
    label: str,
    coro: Coroutine[Any, Any, Any],
    *,
    detail_fn: Callable[[Any], str] | None = None,
) -> Any | None:
    """Await *coro* and record pass/fail. Return the result or None."""
    try:
        result = await _retry_flaky(coro)
        detail = detail_fn(result) if detail_fn else ""
        ok(label, detail)
        return result
    except Exception as exc:
        fail(label, exc)
        traceback.print_exc()
        return None


# ──────────────────────────────────────────────────────────────────────────────
async def test_system(p: PaperlessClient) -> None:
    _hdr("System: status / statistics / remote_version")

    await check(
        "status()",
        p.status(),
        detail_fn=lambda r: f"db={r.database.status.value if r.database else '?'}",
    )
    await check(
        "statistics()",
        p.statistics(),
        detail_fn=lambda r: f"total_docs={r.documents_total}",
    )
    await check(
        "remote_version()",
        p.remote_version(),
        detail_fn=lambda r: f"version={r.version}, update_available={r.update_available}",
    )


# ──────────────────────────────────────────────────────────────────────────────
async def test_search(p: PaperlessClient) -> None:
    _hdr("Search")

    await check(
        "search('invoice')",
        p.search("invoice"),
        detail_fn=lambda r: (
            f"total={r.total}, documents={len(r.documents or [])}, tags={len(r.tags or [])}"
        ),
    )

    q = SearchQuery("invoice") & SearchQuery.field("tag", "unpaid")
    await check(
        "search(SearchQuery builder)",
        p.search(q),
        detail_fn=lambda r: f"total={r.total}, query={str(q)!r}",
    )


# ──────────────────────────────────────────────────────────────────────────────
async def test_config(p: PaperlessClient) -> None:
    _hdr("Config")

    await check("config()", p.config(), detail_fn=lambda r: f"id={r.id}")


# ──────────────────────────────────────────────────────────────────────────────
async def test_documents(p: PaperlessClient) -> None:
    _hdr("Documents – fetch, iterate, search, more_like, pages")

    # Fetch by pk
    doc = await check(
        f"documents({TEST_DOCUMENT_ID})",
        p.documents(TEST_DOCUMENT_ID),
        detail_fn=lambda r: f"title={r.title!r}",
    )

    # Fetch with permissions
    async with p.documents.with_permissions():
        await check(
            f"documents({TEST_DOCUMENT_ID}) with permissions",
            p.documents(TEST_DOCUMENT_ID),
            detail_fn=lambda r: f"has_permissions={r.has_permissions}",
        )

    # Lazy fetch
    await check(
        f"documents({TEST_DOCUMENT_ID}, lazy=True)",
        p.documents(TEST_DOCUMENT_ID, lazy=True),
        detail_fn=lambda r: f"id={r.id}",
    )

    # pages() iteration
    try:
        pages = aiter(p.documents.pages(page=1, page_size=PAGE_SIZE))
        page = await anext(pages)
        ok(
            f"documents.pages(page=1, page_size={PAGE_SIZE})",
            f"count={page.count}, items_on_page={page.current_count}",
        )
    except Exception as exc:
        fail("documents.pages()", exc)

    # as_list / as_dict shortcuts (limit via filter)
    try:
        async with p.documents.filter(page_size=PAGE_SIZE):
            docs_list = await p.documents.as_list()
        ok(f"documents.as_list() [page_size={PAGE_SIZE}]", f"len={len(docs_list)}")
    except Exception as exc:
        fail("documents.as_list()", exc)

    try:
        async with p.documents.filter(page_size=PAGE_SIZE):
            docs_dict = await p.documents.as_dict()
        ok(f"documents.as_dict() [page_size={PAGE_SIZE}]", f"len={len(docs_dict)}")
    except Exception as exc:
        fail("documents.as_dict()", exc)

    # search
    try:
        results = [d async for d in p.documents.search("invoice")]
