---
name: Linting

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - "pypaperless/**"
      - "tests/**"
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  lint:
    name: ${{ matrix.tool }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [codespell, ruff, prek-hooks, yamllint]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.2
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🏗 Set up uv
        run: |
          pipx install uv
          uv venv
      - name: 🏗 Install Python dependencies
        run: uv sync --group dev
      - name: 🚀 Execute checks
        run: |
          if [ "${{ matrix.tool }}" = "codespell" ]; then
            uv run prek run codespell --all-files
          elif [ "${{ matrix.tool }}" = "ruff" ]; then
            uv run ruff check --output-format=github .
            uv run ruff format --check .
          elif [ "${{ matrix.tool }}" = "prek-hooks" ]; then
            uv run prek run check-ast --all-files
            uv run prek run check-case-conflict --all-files
            uv run prek run check-docstring-first --all-files
            uv run prek run check-json --all-files
            uv run prek run check-merge-conflict --all-files
            uv run prek run check-symlinks --all-files
            uv run prek run check-toml --all-files
            uv run prek run check-yaml --all-files
            uv run prek run detect-private-key --all-files
            uv run prek run end-of-file-fixer --all-files
            uv run prek run trailing-whitespace --all-files
          elif [ "${{ matrix.tool }}" = "yamllint" ]; then
            uv run yamllint .
          fi
