---
name: Testing

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - "pypaperless/**"
      - "tests/**"
      - ".github/workflows/tests.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COVERAGE_PYTHON: "3.14"

jobs:
  pytest:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.13", "3.14"]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v7.0.0
      - name: 🏗 Set up Python ${{ matrix.python }}
        id: python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: ${{ matrix.python }}
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: 🏗 Install Python dependencies
        run: uv sync --group dev
      - name: 🚀 Run pytest
        run: uv run pytest -v --cov-report xml:coverage.xml --cov pypaperless tests
      - name: 🚀 Upload coverage report
        if: matrix.python == env.COVERAGE_PYTHON
        uses: codecov/codecov-action@v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
