---
name: Typing

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
      - "pypaperless/**"
      - "tests/**"
      - ".github/workflows/typing.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: "3.14"

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6.0.3
      - name: 🏗 Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@v8.3.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: 🏗 Install Python dependencies
        run: uv sync --group dev
      - name: 🚀 Run mypy
        run: uv run mypy pypaperless
